### PR TITLE
Lunch time, refactored particles

### PR DESCRIPTION
**Pull request by ScottHolden**
*shrug*

### CODE REVIEW

**Comment by davidwengier** [comment]
Oh good, more things I don't understand :P

**Comment by ScottHolden** [comment]
It's simpler :P 
Trying to remove complexity. Also, we should probably look at webpack at some stage?

**Comment by davidwengier** [comment]
I just made a batch file ¯\_(ツ)_/¯

**Comment by ScottHolden** [comment]
I've just been going 'tsc -p .' but more that it would pack it into a single JS file, so we don't have a million js files :P

**Comment by davidwengier** [comment]
Oh yeah, thats probably worth doing. tsc will do that, but not with CommonJS modules, and it doesn't compile with amd or system. I've just been using VS Code, but silently dreading the first time I have to add a new JS file.

**Pull request merged**
