### PR TITLE
TSLint with AMD module loader (via AlmondJS)

### PR DESCRIPTION
**Pull request by ScottHolden**
Why did I think this would be a fun idea.....

All renames finished, TSLint is happy.

### CODE REVIEW

**Comment by ScottHolden** [comment]
I apologize for this pull.

Maybe don't merge it just yet :/

**Comment by davidwengier** [comment]
I remain forever amazed at how you can know so much cloudy stuff, but also keep up on the front end javascript ecosystem. Meanwhile I'm just over here trying to understand a single technology stack :P

**Comment by ScottHolden** [comment]
Hahaha, I'm just winging it :P

**Comment by ScottHolden** [comment]
Yolo, merging. Good luck everybody!

**Pull request merged**
