### PR TITLE
Track sprite refactor

### PR DESCRIPTION
**Pull request by ScottHolden**
How do you feel about this for sprite management?

A little bit easier to see how each track is drawn, and each piece is rendered once, then drawn as needed :)

There is an 'off by 0.5' bug somewhere, as the track is blurry!

Also, thoughts on file structure and naming? Getting a few more files now :)

### CODE REVIEW

**Comment by davidwengier** [comment]
Initial thoughts on naming: why does every file start with "play"?!! 😛

**Comment by ScottHolden** [comment]
Got it, anything outstanding pull request wise before we rename all the files and fix the structure? :)

**Comment by davidwengier** [comment]
Just this.

**Comment by ScottHolden** [comment]
Cool, started the restructure, feeling a lot cleaner :)

Also fixed the blurry bug, so it should look crisp on all devices when using the sprite base :)

**Comment by davidwengier** [comment]
Based on your last comment, it seems this is not "DO NOT MERGE" anymore?

**Comment by ScottHolden** [comment]
Yep, this is good to merge, not everything is renamed/sorted, but it's a good start

**Comment by davidwengier** [comment]
Either you reverted the 4 plank corners, or I stuffed up the merge :(

**Comment by ScottHolden** [comment]
I reverted the 4 plank corners, as there was a drawing bug (edges left behind when clearing a cell)

**Pull request merged**
